tools:
    external_code_coverage:
        timeout: 600
    php_sim: true
    php_pdepend: true
    php_analyzer:
        dependency_paths: [contao/]
    sensiolabs_security_checker: true

filter:
    paths: [src/*]
    excluded_paths: [src/Resources/*]
