tools:
    external_code_coverage:
        timeout: 900
    php_sim: true
    php_pdepend: true
    php_analyzer:
        dependency_paths:
            - src/Resources/contao/classes/
            - src/Resources/contao/controllers/
            - src/Resources/contao/drivers/
            - src/Resources/contao/elements/
            - src/Resources/contao/forms/
            - src/Resources/contao/library/
            - src/Resources/contao/models/
            - src/Resources/contao/modules/
            - src/Resources/contao/pages/
            - src/Resources/contao/widgets/
    sensiolabs_security_checker: true

filter:
    paths: [src/*]
    excluded_paths: [src/Resources/*]
