language: php

php:
  - "5.5"
  - "5.6"
  - "nightly"

  # FIXME: Class Mock_Kernel_1fff02ed contains abstract method (registerBundles) and must therefore be declared
  # abstract or implement the remaining methods
  #- "hhvm"

sudo: false

matrix:
  include:
    - php: 5.5
      env: deps=highest
    - php: 5.6
      env: deps=lowest

before_install:
  - composer selfupdate
  - if [ -z "$deps" ]; then composer install --prefer-source; fi;
  - if [ "$deps" = "lowest" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi;
  - if [ "$deps" = "highest" ]; then composer update --prefer-source; fi;

script:
  - ./vendor/bin/phpunit --testsuite latest --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
