language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"
    - "nightly"

sudo: false

before_script:
    - composer selfupdate
    - composer install

script:
    - ./vendor/bin/phpunit --testsuite latest --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
