services:
    contao.clearer.internal_cache:
        class: Contao\CoreBundle\Cache\ContaoCacheClearer
        public: false
        arguments:
            - "@filesystem"
        tags:
            - { name: kernel.cache_clearer }

    contao.warmer.internal_cache:
        class: Contao\CoreBundle\Cache\ContaoCacheWarmer
        public: false
        arguments:
            - "@filesystem"
            - "@contao.resource_finder"
            - "@contao.resource_locator"
            - "%kernel.root_dir%"
            - "@doctrine.dbal.default_connection"
        tags:
            - { name: kernel.cache_warmer }
