services:
    contao.command.automator:
        class: Contao\CoreBundle\Command\AutomatorCommand
        calls:
            - ["setFramework", ["@contao.framework"]]
        tags:
            -  { name: console.command }

    contao.command.filesync:
        class: Contao\CoreBundle\Command\FilesyncCommand
        calls:
            - ["setFramework", ["@contao.framework"]]
        tags:
            -  { name: console.command }

    contao.command.install:
        class: Contao\CoreBundle\Command\InstallCommand
        tags:
            -  { name: console.command }

    contao.command.symlinks:
        class: Contao\CoreBundle\Command\SymlinksCommand
        tags:
            -  { name: console.command }

    contao.command.version:
        class: Contao\CoreBundle\Command\VersionCommand
        tags:
            -  { name: console.command }



    # TODO this should be done in a compiler pass

    doctrine.migrations.diff_command:
        class: Doctrine\Bundle\MigrationsBundle\Command\MigrationsDiffDoctrineCommand
        arguments:
            - "@contao.doctrine.composite_schema_provider"
        tags:
            - { name: console.command }

    contao.doctrine.dca_schema_provider:
        class: Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider
        arguments:
            - "@contao.framework"
            - "@database_connection"

    contao.doctrine.orm_schema_provider:
        class: Doctrine\DBAL\Migrations\Provider\OrmSchemaProvider
        arguments:
            - "@doctrine.orm.entity_manager"

    contao.doctrine.composite_schema_provider:
        class: Contao\CoreBundle\Doctrine\Schema\CompositeSchemaProvider
        calls:
            - ["add", ["@contao.doctrine.orm_schema_provider"]]
            - ["add", ["@contao.doctrine.dca_schema_provider"]]
