services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            # Priority must be higher than any other listener that uses the Contao framework and lower than the
            # priority of the route_listener, which defaults to 32.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.exception:
        class: Contao\CoreBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments:
            - "%contao.pretty_error_screens%"
            - "@templating"
            - "@contao.adapter.config"

    contao.listener.initialize_system:
        class: Contao\CoreBundle\EventListener\InitializeSystemListener
        arguments:
            - "@router"
            - "@session"
            - "%kernel.root_dir%"
            - "@security.csrf.token_manager"
            - "%contao.csrf_token_name%"
            - "@contao.adapter.config"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be higher than any other listener that uses the Contao framework and lower than the
            # priority of the route_listener and the container_scope listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 26 }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be lower than the one of the toggle_view listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 22 }

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - "@contao.referer_id.manager"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be higher than the one of the Contao initialize system listener and lower than
            # the container_scope listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 28 }

    contao.listener.session:
        class: Contao\CoreBundle\EventListener\SessionListener
        arguments:
            - "@session"
        tags:
            # Priority must be lower than Symfony\Bundle\FrameworkBundle\EventListener\SessionListener (default 128)
            # but higher than the one of the Contao initialize system listener.
            - { name: kernel.event_listener, event: kernel.request, method: registerContaoAttributeBags, priority: 64 }
            - { name: kernel.event_listener, event: console.command, method: registerContaoAttributeBags, priority: 64 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be lower than the one of the initialize_system listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 24 }
