services:
    contao.resource_finder:
        class: Contao\CoreBundle\Config\ResourceFinder
        arguments:
            - "%contao.resources_paths%"

    contao.resource_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
            - "%contao.resources_paths%"
