services:
    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        public: false
        arguments:
            - "%contao.url_suffix%"
            - "%contao.prepend_locale%"
        tags:
            - { name: routing.loader }
