contao_backend:
    path: /contao{_trailing_slash}
    defaults:
        _controller: ContaoCoreBundle:Backend:main
        _trailing_slash: /
        _scope: backend
    requirements:
        _trailing_slash: /?

contao_backend_login:
    path: /contao/login
    defaults:
        _controller: ContaoCoreBundle:Backend:login
        _scope: backend

contao_backend_install:
    path: /contao/install
    defaults:
        _controller: ContaoCoreBundle:Backend:install
        _scope: backend

contao_backend_password:
    path: /contao/password
    defaults:
        _controller: ContaoCoreBundle:Backend:password
        _scope: backend

contao_backend_preview:
    path: /contao/preview
    defaults:
        _controller: ContaoCoreBundle:Backend:preview
        _scope: backend

contao_backend_changelog:
    path: /contao/changelog
    defaults:
        _controller: ContaoCoreBundle:Backend:changelog
        _scope: backend

contao_backend_confirm:
    path: /contao/confirm
    defaults:
        _controller: ContaoCoreBundle:Backend:confirm
        _scope: backend

contao_backend_file:
    path: /contao/file
    defaults:
        _controller: ContaoCoreBundle:Backend:file
        _scope: backend

contao_backend_help:
    path: /contao/help
    defaults:
        _controller: ContaoCoreBundle:Backend:help
        _scope: backend

contao_backend_page:
    path: /contao/page
    defaults:
        _controller: ContaoCoreBundle:Backend:page
        _scope: backend

contao_backend_popup:
    path: /contao/popup
    defaults:
        _controller: ContaoCoreBundle:Backend:popup
        _scope: backend

contao_backend_switch:
    path: /contao/switch
    defaults:
        _controller: ContaoCoreBundle:Backend:switch
        _scope: backend
