services:
    contao.security.authenticator:
        class: Contao\CoreBundle\Security\ContaoAuthenticator
        public: false
        arguments:
            - "@contao.security.user_provider"

    contao.security.user_provider:
        class: Contao\CoreBundle\Security\User\ContaoUserProvider
        public: false
