services:
    contao.data_collector:
        class: Contao\CoreBundle\DataCollector\ContaoDataCollector
        public: false
        arguments:
            - "@service_container"
            - "%kernel.packages%"
        tags:
            - { name: data_collector, template: "ContaoCoreBundle:Collector:contao", id: "contao" }

    contao.image.image_sizes:
        class: Contao\CoreBundle\Image\ImageSizes
        arguments:
            - "@database_connection"
            - "@event_dispatcher"
            - "@contao.framework"

    contao.framework:
        class: Contao\CoreBundle\Framework\ContaoFramework
        arguments:
            - "@request_stack"
            - "@router"
            - "@session"
            - "%kernel.root_dir%"
            - "%contao.error_level%"
        calls:
            - ["setContainer", ["@service_container"]]

    contao.referer_id.manager:
         class: "%security.csrf.token_manager.class%"
         public: false
         arguments:
            - "@contao.referer_id.token_generator"
            - "@security.csrf.token_storage"

    contao.referer_id.token_generator:
         class: Contao\CoreBundle\Referer\TokenGenerator
         public: false

    contao.resource_finder:
        class: Contao\CoreBundle\Config\ResourceFinder
        arguments:
            - "%contao.resources_paths%"

    contao.resource_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
            - "%contao.resources_paths%"

    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        public: false
        arguments:
            - "%contao.prepend_locale%"
        tags:
            - { name: routing.loader }

    contao.security.authenticator:
        class: Contao\CoreBundle\Security\ContaoAuthenticator
        public: false
        calls:
            - ["setContainer", ["@service_container"]]

    contao.security.user_provider:
        class: Contao\CoreBundle\Security\User\ContaoUserProvider
        public: false
        arguments:
            - "@service_container"
            - "@contao.framework"

    contao.image.imagine:
        class: "%contao.image.imagine.class%"
        public: false

    contao.image.image_factory:
        class: Contao\CoreBundle\Image\ImageFactory
        arguments:
            - "@contao.image.imagine"
            - "@contao.adapter.config"
            - "@contao.adapter.model_repository"
            - "@filesystem"

    contao.image.picture_factory:
        class: Contao\CoreBundle\Image\PictureFactory
        arguments:
            - "@contao.image.factory"
            - "@contao.adapter.model_repository"
