services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            # Priority must be higher than any other listener that uses the Contao framework and lower than the
            # priority of the route_listener, which defaults to 32.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.initialize_system:
        class: Contao\CoreBundle\EventListener\InitializeSystemListener
        arguments:
            - "@router"
            - "@security.csrf.token_manager"
            - "@session"
            - "%kernel.root_dir%"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be higher than any other listener that uses the Contao framework and lower than the
            # priority of the route_listener and the container_scope listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 28 }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be lower than the one of the toggle_view listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 24 }

    contao.listener.session:
        class: Contao\CoreBundle\EventListener\SessionListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: registerContaoAttributeBags, priority: 64 }
            - { name: kernel.event_listener, event: console.command, method: registerContaoAttributeBags, priority: 64 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            # Priority must be lower than the one of the initialize_system listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 26 }

    contao.resource_locator.bundles:
        class: Contao\CoreBundle\Config\FileLocator
        public: false
        factory: [Contao\CoreBundle\Config\FileLocator, createFromKernelBundles]
        arguments:
            - "@kernel"
        tags:
            - { name: contao.resource_locator }

    contao.resource_locator.chain:
        class: Contao\CoreBundle\Config\ChainFileLocator
        public: false

    contao.resource_locator.cache:
        class: Contao\CoreBundle\Config\CombinedFileLocator
        public: false
        arguments:
            - '%kernel.cache_dir%/contao'
            - "@contao.resource_locator"

    contao.resource_locator:
        alias: contao.resource_locator.bundles

    contao.cached_resource_locator:
        alias: contao.resource_locator.cache

    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        arguments:
            - "%contao.url_suffix%"
            - "%locale%"
            - "%contao.prepend_locale%"
        tags:
            - { name: routing.loader }

    contao.security.authenticator:
        class: Contao\CoreBundle\Security\ContaoAuthenticator
        public: false
        arguments:
            - "@contao.security.user_provider"

    contao.security.user_provider:
        class: Contao\CoreBundle\Security\User\ContaoUserProvider
        public: false

    contao.web_profiler.data_collector:
        class: Contao\CoreBundle\DataCollector\ContaoDataCollector
        arguments:
            - '%kernel.packages%'
        tags:
            - { name: data_collector, template: "ContaoCoreBundle:Collector:contao", id: "contao" }
