services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 254 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.legacy_script:
        class: Contao\CoreBundle\EventListener\LegacyScriptListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 150 }

    contao.routing.backend_loader:
        parent: routing.bundle_resource_loader
        arguments:
            - "@@ContaoCoreBundle/Resources/config/routing.yml"
        tags:
            - { name: routing.bundle_loader, priority: 200 }

    contao.routing.dev_loader:
        parent: routing.bundle_resource_loader
        arguments:
            - "@@ContaoCoreBundle/Resources/config/routing_dev.yml"
            - ["dev", "test"]
        tags:
            - { name: routing.bundle_loader }

    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        tags:
            - { name: routing.bundle_loader, priority: -250 }

    data_collector.contao:
        class: Contao\CoreBundle\DataCollector\ContaoDataCollector
        tags:
            - { name: data_collector, template: "ContaoCoreBundle:Collector:contao", id: "contao" }

    contao_user_provider:
        class: Contao\CoreBundle\Security\User\ContaoUserProvider

    contao_authenticator:
        class: Contao\CoreBundle\Security\ContaoAuthenticator
        arguments: ["@contao_user_provider"]
