services:
    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 150 }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 254 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
